### ISSUE TITLE
build error with liquibook_test

### ISSUE THREAD

**Issue by Jiachen777** [mkipnis/DistributedATS#12]
Hi @mkipnis ,

This a fancy project, and I'm trying to build it from source.
When using download_deps_and_build_all.sh, I met this error that I cannot find any solution.
Would you please help me? DEPS_BUILD_DIR is `/data_ssd/DistributedATS/build/`
It seems like these error logs were printed by download_deps_and_build_all.sh:90

```+ /data_ssd/DistributedATS/build/OpenDDS-3.22/ACE_wrappers/bin/mwc.pl -type gnuace
MPC_ROOT was set to /data_ssd/MPC/.
Using .../OpenDDS-3.22/ACE_wrappers/bin/MakeProjectCreator/config/MPC.cfg
Generating 'gnuace' output using default input
liquibook_unit.mpc: line 1:
ERROR: Unable to locate parent: liquibook_test
ERROR: Unable to process build/liquibook-2.0.0/test/unit/liquibook_unit.mpc
ERROR: Unable to process: default input
+ make realclean
make: *** No rule to make target 'realclean'.  Stop.
+ make
make: *** No targets specified and no makefile found.  Stop.
```

Maybe I missed some prerequisites?

**Comment by mkipnis** [comment]
Hi @Jiachen777,

Please provide me with the content of the following directory:
$HOME/distributed_ats_deps_build
And the content of the following file in the project's root: distributed_ats_env.sh

Thanks,
Mike

**Comment by Jiachen777** [comment]
This is $HOME/distributed_ats_deps_build:
```
~/distributed_ats_deps_build$ ls -la
total 48272
drwxrwxr-x 10 meex meex     4096 Jul  5 10:05 .
drwxr-xr-x  3 meex meex     4096 Jul  5 12:35 ..
drwxr-xr-x  2 meex meex     4096 Jul  5 10:05 bin
-rw-rw-r--  1 meex meex      195 Jul  5 10:16 distributed_ats_env.sh
drwxr-xr-x  9 meex meex     4096 Jul  5 10:03 include
drwxr-xr-x  3 meex meex     4096 Jul  5 10:05 lib
drwxrwxr-x  9 meex meex     4096 Feb 22  2017 liquibook-2.0.0
-rw-rw-r--  1 meex meex   276366 Jul  5 09:42 liquibook-2.0.0.tar.gz
drwxr-xr-x 19 meex meex     4096 Jul  5 10:16 OpenDDS-3.22
-rw-rw-r--  1 meex meex 21032404 Jul  5 09:42 OpenDDS-3.22.tar.gz
drwxrwxr-x 14 meex meex     4096 Jul  5 10:16 quickfix-1.15.1
-rw-rw-r--  1 meex meex 15919362 Jul  5 09:42 quickfix-v1.15.1.tar.gz
drwxr-xr-x  6 meex meex     4096 Jul  5 10:00 share
-rw-rw-r--  1 meex meex 12152049 Jul  5 09:42 sqlite-3.39.4.tar.gz
drwxrwxr-x 16 meex meex     4096 Jul  5 10:16 sqlite-version-3.39.4
```

and the file `/data_ssd/DistributedATS/distributed_ats_env.sh` you asked:
```
/data_ssd/DistributedATS$ cat distributed_ats_env.sh 

. /data_ssd/DistributedATS/build/OpenDDS-3.22/setenv.sh

export QUICKFIX_HOME=/data_ssd/DistributedATS/build
export LIQUIDBOOK_HOME=/data_ssd/DistributedATS/build/liquibook-2.0.0
export SQLITE_HOME=/data_ssd/DistributedATS/build
export DATS_HOME=/data_ssd/DistributedATS
export LD_LIBRARY_PATH=:/lib:/lib:/data_ssd/DistributedATS/lib:/data_ssd/DistributedATS/build/lib
```

I also find same name file under `~/distributed_ats_deps_build/`, but it has different content,
```
~/distributed_ats_deps_build$ cat distributed_ats_env.sh 

. -h/OpenDDS-3.22/setenv.sh

export QUICKFIX_HOME=-h
export LIQUIDBOOK_HOME=-h/liquibook-2.0.0
export SQLITE_HOME=-h
export DATS_HOME=/data_ssd/DistributedATS
export LD_LIBRARY_PATH=:/lib:/lib
```

`/data_ssd/DistributedATS/distributed_ats_env.sh` is different than  `~/distributed_ats_deps_build/distributed_ats_env.sh`, I missed any configuration?

Thanks a lot

**Comment by mkipnis** [comment]
Hi @Jiachen777,

The environment doesn't look right.  Please delete the following folder and files
/data_ssd/DistributedATS
~/distributed_ats_deps_build/distributed_ats_env.sh
/data_ssd/DistributedATS/distributed_ats_env.sh
```
rm -rf /data_ssd/DistributedATS
rm ~/distributed_ats_deps_build/distributed_ats_env.sh
rm /data_ssd/DistributedATS/distributed_ats_env.sh
```

and run download_deps_and_build_all.sh in /data_ssd/DistributedATS again 
```
$ cd /data_ssd/DistributedATS
$ ./download_deps_and_build_all.sh
```

Once the command above complete, let's check if all dependencies(OpenDDS/QuickFIX/SQLITE) were properly built.  Open a new terminal window and go to /data_ssd/DistributedATS
Source  distributed_ats_env.sh, configure Makefiles, and try building the project:

```
$ cd /data_ssd/DistributedATS/
$ . ./distributed_ats_env.sh
$ $ACE_ROOT/bin/mwc.pl -type gnuace
$ make
```

Once the build is complete, see the content of the bin directory:
```
$ ls -ltr $DATS_HOME/bin
```
If you see the following three exec file when everything is fine, overwise, provide me with the errors from the build:
```
DataService -> ../DataService/src/DataService
FIXGateway -> ../FIXGateway/src/FIXGateway
MatchingEngine -> ../MatchingEngine/src/MatchingEngine
```

If everything is ok, try starting the ATS:
```
$ cd $DATS_HOME/MiscATS/CryptoCLOB/scripts/
$ ./start_ats.sh
```
Once if you see the following statements:
```
DataService [data_service_a.ini] is running - ###
DataService [data_service_b.ini] is running - ###
MatchingEngine [matching_engine_MARKET_BTC.ini] is running - ###
MatchingEngine [matching_engine_MARKET_ETH.ini] is running - ###
MatchingEngine [matching_engine_MARKET_OTHER_COIN.ini] is running - ###
FIXGateway [fix_gwy_1.cfg] is running - ###
FIXGateway [fix_gwy_2.cfg] is running - ###
FIXGateway [fix_gwy_3.cfg] is running - ###
```

At this point you may proceed with building an experimental front-end, see the instructions below:
https://github.com/mkipnis/DistributedATS/tree/master/MiscClients/spring_reactjs

Upon the start of the front-end, use CRYPTO_TRADER_1 - CRYPTO_TRADER_4 Password: TEST to login and trade.

**Comment by mkipnis** [comment]
Hi @Jiachen777,

download_deps_and_build_all.sh should download and build all the prerequisites.  Also, the project is dockerized so you may use it without compiling. https://github.com/mkipnis/DistributedATS/tree/master/docker

Let's check if you have all of them properly compiled.  After you run download_deps_and_build_all.sh, you should see the following file: distributed_ats_env.sh
Please source that file, and check if you have files in OpenDDS and QuickFIX directories:
```
. ./distributed_ats_env.sh
$ ls -ltr $QUICKFIX_HOME/lib
$ ls -ltr $DDS_ROOT/lib 
```
if you see the files in the listed above directories, the try rebuilding DistributedATS by running the following command:
```
$ $ACE_ROOT/bin/mwc.pl -type gnuace
$ make realclean
$ make
```
