### ISSUE TITLE
Build Doubts

### ISSUE THREAD

**Issue by Menniti** [mkipnis/DistributedATS#8]
Hello @mkipnis 

I'm having doubts how can I build the project.

I have setup the
download_deps_and_build_all.sh

It download in a diff path, seems to be ok

And I have run this command

`./DCPSInfoRepo -ORBEndpoint iiop://localhost:12345 -DCPSDebugLevel=0 -ORBLogFile /home/menniti/DistributedATS/MiscATS/MultiMatchingEngineATS/logs/DCPSInfoRepo.log`

Seems to be working,
![image](https://user-images.githubusercontent.com/15658494/232567422-2f9ffd9a-c782-4bb2-8fb5-1695c40d9163.png)

but when I tried to start using ./scripts/start.sh

it always return error saying the /bin/DataService or /bin/FIXGateway not founded, 

![image](https://user-images.githubusercontent.com/15658494/232567539-808edc98-e0e9-47a2-b437-ff9bfbc7d1ed.png)

So when I try to build it, I could not do it.

Can you help me with it?
Thankss

**Comment by mkipnis** [comment]
Hi Luiz,

Upon the successful build of the project, you should see the following file, "distributed_ats_env.sh", in the project's root directory.

You will need to source that file by running the command: ". ./distributed_ats_env.sh"

Once that file is sourced, you can check if you have FIXGateway, DataService, and MatchingEngine in your $DATS_HOME/bin directory by running the following command:
ls -ltr $DATS_HOME/bin

dats@ubuntu-s-4vcpu-8gb-amd-nyc3-01:~/DistributedATS$ ls -ltr $DATS_HOME/bin
total 0
lrwxrwxrwx 1 dats dats 30 Feb 11 15:19 DataService -> ../DataService/src/DataService
lrwxrwxrwx 1 dats dats 28 Feb 11 15:29 FIXGateway -> ../FIXGateway/src/FIXGateway
lrwxrwxrwx 1 dats dats 36 Feb 11 15:32 MatchingEngine -> ../MatchingEngine/src/MatchingEngine

Let me know if any of these three files are missing, so we can research issues in your dev environment.

If you have all three components built and available in the $DATS_HOME/bin directory, you can navigate to the directory where the multi-matching engine ATS is located and start it using the following command:

cd $DATS_HOME/MiscATS/MultiMatchingEngineATS/scripts
and run:
./start_ats.sh

This command will start two matching engies, three gateways, and two dataservices
Wait for a minute or so for all components to initialize, and you should see the following:

DataService [data_service_a.ini] is running - 43631
DataService [data_service_b.ini] is running - 43647
MatchingEngine [matching_engine_MARKET_Y.ini] is running - 43663
MatchingEngine [matching_engine_MARKET_Z.ini] is running - 43679
FIXGateway [fix_gwy_1.cfg] is running - 43695
FIXGateway [fix_gwy_2.cfg] is running - 43710
FIXGateway [fix_gwy_3.cfg] is running - 43726

Once the system is up and running, you may start the front-end:
Open another terminal, navigate to MiscClient/spring_reactjs in your project's root, and follow the instructions in README.md

Once the spring-boot is up, you may login as TRADER_1, TRADER_2, TRADER_3, TRADER_4.  Password: TEST, from the http://localhost:8080/index.html in your browser, and start trading.

Hope this helps.
Best Regards,
Mike
